name:                net-firewall-simulator
version:             0.1.0.0
github:              "maph420/net-firewall-simulator"
license:             Apache-2.0
author:              "Juan Ignacio Bertoni"
maintainer:          "juani.bertoni73@gmail.com"
copyright:           "2026 Juan Ignacio Bertoni"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/maph420/net-firewall-simulator#readme>

dependencies:
- base >= 4.7 && < 5
- array
- ip
- text
- mtl # chequear
- containers # chequear
- prettyprinter

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  net-firewall-simulator-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - net-firewall-simulator
    build-tools:
    - happy

tests:
  net-firewall-simulator-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - net-firewall-simulator
